name: Build LaTeX document
on: [push]
jobs:
    build_latex:
        runs-on: ubuntu-latest
        steps:
            - name: setup repo
              uses: actions/checkout@v4
            - name: compile doc
              uses: xu-cheng/latex-action@v3
              with:
                root_file: Thesis.tex
                latexmk_use_lualatex: true
            - name: upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: PDF
                path: Thesis.pdf