name: Build Thesis PDF

on:
  push:
    branches: [main]      # Change 'main' to your default branch if needed
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Compile Thesis with LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: Thesis.tex
          texlive_version: 2024

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Thesis PDF
          path: Thesis.pdf

  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Download PDF artifact
        uses: actions/download-artifact@v4
        with:
          name: Thesis PDF

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: Thesis.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}