name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate Book PDF
        uses: hspaans/latexmk-action@v2.0.0
        with:
          format: pdf
          filename: Thesis.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: compiled-book
          path: Thesis.pdf

      - name: Upload to Release (Release Only)
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Thesis.pdf
          token: ${{ secrets.GITHUB_TOKEN }}